# Generated by Django 2.2.3 on 2019-08-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdWatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdWatch.TipoAnuncio'),
        ),
    ]
