# Generated by Django 2.2.4 on 2019-08-03 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('AdWatch', '0004_auto_20190802_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='horariotrans',
            options={'verbose_name': 'Hora de Transmisión', 'verbose_name_plural': 'Horas de Transmisión'},
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='audioAnuncio',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audios-adwatch', validators=[django.core.validators.FileExtensionValidator(['wav'])], verbose_name='Archivo de Audio'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='frecuencia',
            field=models.ForeignKey(default=97.5, on_delete=django.db.models.deletion.CASCADE, to='AdWatch.Frecuencia'),
            preserve_default=False,
        ),
    ]
