# Generated by Django 2.2.4 on 2019-08-04 01:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdWatch', '0006_auto_20190803_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='frecuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdWatch.Frecuencia'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdWatch.TipoAnuncio'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='direccion',
            field=models.DecimalField(decimal_places=1, max_digits=5, unique=True, validators=[django.core.validators.MinValueValidator(88.1), django.core.validators.MaxValueValidator(107.9)]),
        ),
        migrations.AlterField(
            model_name='tipoanuncio',
            name='descripcion',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tipoanuncio',
            name='tipo',
            field=models.CharField(max_length=32),
        ),
    ]
